version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./site.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
        networks:
            - code-network
    php:
        build: ./docker/php/
        volumes:
            - ./code:/code
        networks:
            - code-network
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: laravel
            MYSQL_DATABASE: laravel
        ports:
            - 3306:3306        
        networks:
            - code-network

networks:
    code-network:
        driver: bridge

